### ISSUE TITLE
Mockup Screen

### ISSUE THREAD

**Issue by levidasilvalima** [m1ojo/miojo#3]
Begin mockup project of user profile, dashboard, login

**Comment by Diegovisk** [comment]
@levidasilvalima be aware that this is a duplicate of [#2](https://github.com/m1ojo/miojo-app/issues/2) in the correct repo: miojo-app. :)

**Comment by RodrigoCMoraes** [comment]
@Mozz4rt is a good idea tell what is the original issue when telling that one is duplicated.
